//--------------------------------------------------
// <auto-generated>
//     Assembly Version
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//--------------------------------------------------

using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Cashier")]
[assembly: AssemblyCopyright("2011")]
[assembly: AssemblyVersion(AssemblyRevision.FullVersion)]
[assembly: AssemblyFileVersion(AssemblyRevision.FullVersion)]
[assembly: NeutralResourcesLanguage("en-US")]

internal static class AssemblyRevision
{
    public const string Major = "1";
    public const string Minor = "0";
    public const string Build = "0";
    public const string Revision = "4";

    public const string MainVersion = Major + "." + Minor;
    public const string FullVersion = Major + "." + Minor + "." + Build + "." + Revision;

    public const string BuildTime = "2011/10/20 22:29:40";
    public const string RevisionRange = "2:4";
    public const bool RevisionMixed = true;
    public const bool RevisionModified = true;

    #warning Revision modified 
}
