//--------------------------------------------------
// <auto-generated>
//     Assembly Version
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//--------------------------------------------------

using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: ComVisible(false)]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Cashier")]
[assembly: AssemblyCopyright("2011")]
[assembly: AssemblyVersion(AssemblyRevision.FullVersion)]
[assembly: AssemblyFileVersion(AssemblyRevision.FullVersion)]
[assembly: NeutralResourcesLanguage("en-US")]

internal static class AssemblyRevision
{
    public const string Major = "1";
    public const string Minor = "1";
    public const string Build = "0";
    public const string Revision = "$WCREV$";

    public const string MainVersion = Major + "." + Minor;
    public const string FullVersion = Major + "." + Minor + "." + Build + "." + Revision;

    public const string BuildTime = "$WCNOW$";
    public const string RevisionRange = "$WCRANGE$";
    public const bool RevisionMixed = $WCMIXED?true:false$;
    public const bool RevisionModified = $WCMODS?true:false$;

    $WCMODS?#warning Revision modified:$ 
}
